version: '2'
services:
  client:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
      - '35729:35729'
    volumes:
      - ./client:/client
    links:
      - api
    networks:
      - toolbox-network
  api:
    build: ./api
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./api:/api
    networks:
      - toolbox-network
networks:
  toolbox-network:
    driver: bridge
